name: whisper_gui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.3.1
  process_run: ^1.2.4
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
